import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { ChangeEvent, useState } from "react";
import { Button, Grid, TextField, Typography } from "@mui/material";
import { authorizeURL } from "../spotify";
import SpotifyButton from "../components/SpotifyButton";
import Link from "next/link";

type Props = {
  authorizeURL?: string;
};

const Home: NextPage<Props> = ({ authorizeURL }) => {
  const [title, setTitle] = useState("いい感じの名前");

  const handleChange = (event: ChangeEvent<HTMLInputElement>) => {
    setTitle(event.target.value);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>お気に入り変換くん</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {authorizeURL ? (
          <SpotifyButton authorizeURL={authorizeURL} />
        ) : (
          <Grid container spacing={2} textAlign={"center"}>
            <Grid item xs={12} md={6}>
              <Typography variant="h3">プレイリスト名決めてね</Typography>
            </Grid>
            <Grid item xs={12} md={6}>
              <TextField
                label="いい感じの名前"
                variant="outlined"
                sx={{ minWidth: "400px" }}
                onChange={handleChange}
              />
              <Link href={`/getSong?name=${title}`} passHref>
                <Button
                  variant="contained"
                  sx={{ minWidth: "100px", height: "55px" }}
                >
                  送信
                </Button>
              </Link>
            </Grid>
          </Grid>
        )}
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  if (context.req.cookies["access_token"]) {
    return {
      props: {},
    };
  } else {
    return {
      props: {
        authorizeURL: authorizeURL,
      },
    };
  }
};

export default Home;
